pull_request_rules:
  - name: release
    conditions:
      - author=raviqqe
      - check-success=build (ubuntu-latest)
      - check-success=build (macos-latest)
    actions:
      label:
        add:
          - release
