name: build
on:
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew test-bot
      - uses: actions/upload-artifact@v3
        with:
          name: bottles
          path: "*.bottle.*"
