name: release
on:
  pull_request_target:
    types:
      - labeled
jobs:
  release:
    if: contains(github.event.pull_request.labels.*.name, 'release')
    runs-on: ubuntu-latest
    env:
      HOMEBREW_NO_INSTALL_FROM_API: 1
    steps:
      - uses: homebrew/actions/setup-homebrew@master
      - uses: homebrew/actions/git-user-config@master
      - run: brew pr-pull --debug --workflows build.yaml --tap=${{ github.repository }} ${{ github.event.pull_request.number }}
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
      - uses: homebrew/actions/git-try-push@master
        with:
          branch: main
          token: ${{ github.token }}
