name: turtle_release
on:
  pull_request:
jobs:
  tag_check:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.version }}
      should_release: ${{ env.should_release }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          git clone https://github.com/raviqqe/turtle-build
          cd turtle-build
          echo version=$(cat Cargo.toml | grep '^version = ' | cut -f 2 -d '"') >> $GITHUB_ENV
      - run: |
          if ! grep "version '$version'" Formula/turtle.rb; then
            echo should_release=true >> $GITHUB_ENV
          fi
  release:
    needs:
      - tag_check
    if: needs.tag_check.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo version=${{ needs.tag_check.outputs.version }} >> $GITHUB_ENV
      - run: sed -i "s/version .*/version '$version'/" Formula/turtle.rb
      - run: |
          hash=$(curl -fsSL https://github.com/raviqqe/turtle-build/archive/refs/tags/v$version.tar.gz | sha256sum | cut -f 1 -d ' ')
          sed -i "s/sha256 .*/sha256 '$hash'/" Formula/turtle.rb
      - uses: peter-evans/create-pull-request@v3
        with:
          title: Update Turtle
          branch: chore/version/turtle
          base: main
