name: test
on:
  pull_request:
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install --verbose --build-bottle pen-lang/pen/pen
      - run: brew test --verbose pen-lang/pen/pen
