name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: reviewdog/action-rubocop@v1
        with:
          github_token: ${{ secrets.github_token }}
