name: test
on:
  push:
    branches:
      - main
  pull_request:
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        formula:
          - pen
          - turtle
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Homebrew/actions/setup-homebrew@master
      - run: brew install pen-lang/pen/${{ matrix.formula }}
      - run: brew test pen-lang/pen/${{ matrix.formula }}
